version: 2
jobs:
    build_and_test:
        working_directory: ~/rust-monte-carlo-tree-search
        docker:
            - image: rust:latest
        steps:
            - checkout
            - run:
                name: Build application
                working_directory: ~/rust-monte-carlo-tree-search
                command: cargo build
            - run:
                name: Run the tests
                working_directory: ~/rust-monte-carlo-tree-search
                command: cargo test
workflows:
    version: 2
    tests:
        jobs:
            - build_and_test
