version: 2
jobs:
    build:
        working_directory: ~/rust-monte-carlo-tree-search
        docker:
            - image: rust:latest
        steps:
            - checkout
            - run:
                name: Build application
                working_directory: ~/rust-monte-carlo-tree-search
                command: cargo build
workflows:
    version: 2
    tests:
        jobs:
            - build
